### ISSUE TITLE
Settings for IP White Listing

### ISSUE THREAD

**Issue by ricxsar** [rook2pawn/node-ddos#10]
Is it possible to add ip's where it is not checked by the middleware?

For instance, if I have an application where it connects to the other application which is protected by this middleware and executing series of request for data syncing, it should be allowed to do so, so that the operation will not fail.

**Comment by rook2pawn** [comment]
@ricxsar Whitelist issue committed https://github.com/rook2pawn/node-ddos/commit/2640c00a03ac8378b71c135d49bf136db871dd54
