### ISSUE TITLE
It don't seem to work with post request

### ISSUE THREAD

**Issue by quentinbt** [rook2pawn/node-ddos#11]
it works perfectly with any get request but not with post, I'm using default configuration

**Comment by rook2pawn** [comment]
@quentinbt  https://github.com/rook2pawn/node-ddos/commit/978670c55c1e3b7027e6fc686cbe242013591985

Specifically

https://github.com/rook2pawn/node-ddos/commit/978670c55c1e3b7027e6fc686cbe242013591985#diff-438703e4d74335827a58bb2e55faefe8

Let me know if the issue persists and we can continue the discussion! (Share code, etc)
