### ISSUE TITLE
Is there any support for Hapi.js

### ISSUE THREAD

**Issue by hbarve1** [rook2pawn/node-ddos#15]
please release support for Hapi.js

Thank You.

**Comment by rook2pawn** [comment]
@hbarve1  next release includes log and hapi-js support

**Comment by stefanstelzer** [comment]
Still not implemented?

**Comment by rook2pawn** [comment]
@stefanstelzer @hbarve1 I'm happy to announce support for HapiJS! It's fully tested and documented.
I've also updated the readme to be more readable.

**Comment by stefanstelzer** [comment]
Absolutely great!
