### ISSUE TITLE
Cannot find module 'hashish' when using it with HapiJS

### ISSUE THREAD

**Issue by stefanstelzer** [rook2pawn/node-ddos#18]
Hey Folks,

as described in the Title I installed your node_module. But when initializing  it I do get the Error: "Cannot find module 'hashish'".

Any thoughts about this?

Regards, Stefan

**Comment by rook2pawn** [comment]
Ah, thanks for that, fixed https://github.com/rook2pawn/node-ddos/commit/d5fc353adc6473b6c0c09972741bb25fd2226fb2 and republished. Thanks for the report!
