### ISSUE TITLE
535 - Regular Expression Denial of Service

### ISSUE THREAD

**Issue by hubdotcom** [rook2pawn/node-ddos#21]
Vulnerable: < 1.4.1 || > 2.0.0 < 2.0.3 - Patched: >= 1.4.1 < 2.0.0 || >= 2.0.3 - Path: ddos@0.1.24 > response@0.18.0 > mime@1.2.11

**Comment by rook2pawn** [comment]
Thanks! Will look into it.

**Comment by rook2pawn** [comment]
closed [7b2272031e37ba1fe3636c138b34e3527ca49a3f]
