### ISSUE TITLE
another snyk issue - Uninitialized Memory Exposure

### ISSUE THREAD

**Issue by eran10** [rook2pawn/node-ddos#25]
Vulnerable module: bl
Introduced through: ddos@0.1.26
Detailed paths and remediation
Introduced through: ddos@0.1.26 › response@git://github.com/mikeal/response.git#v0.18.1 › bl@0.7.0 
Overview
bl is a storage object for collections of Node Buffers.

A possible memory disclosure vulnerability exists when a value of type number is provided to the append() method and results in concatenation of uninitialized memory to the buffer collection.

This is a result of unobstructed use of the Buffer constructor, whose insecure default constructor increases the odds of memory leakage.

**Comment by eran10** [comment]
?

**Comment by rook2pawn** [comment]
@eran10 no longer using response. thanks for the report.
