### ISSUE TITLE
TypeError: Cannot read property '0' of null

### ISSUE THREAD

**Issue by abhijeet2015** [rook2pawn/node-ddos#31]
![error](https://user-images.githubusercontent.com/11675384/42304063-f7c3ffa2-8041-11e8-8c73-a769c07c4820.PNG)

Error coming after installation of release 0.1.29 - 0.1.31. I am currently using this module on localhost for development env. You have put a validation of regex for ipv4 address from version 0.1.29.

`./lib/index.js  line number - 30`
![error1](https://user-images.githubusercontent.com/11675384/42304190-91dbd1e6-8042-11e8-9966-7cf9ef70a239.PNG)

Have look at this and try to add the validation for localhost also.

**Comment by tobsbola** [comment]
I'm experiencing this same issue too. Thanks

**Comment by hyrious** [comment]
It turns out that `localhost` becomes `::1` at this point, which means it's an ipv6 address.
I haven't tested much.
To temporarily get rid of this, just edit the regexp to
```js
const ipv4re = new RegExp(/\d+\.\d+\.\d+\.\d+|::1$/)
```
For further development, consider use a regexp or [some way](https://github.com/joyent/node-ip6addr) that handles both ipv4 and ipv6 address.

**Comment by MisterHoker** [comment]
My team faced the same issue even with IPv4 address.
We have Express server under IIS reverse proxy.
Value of `address` variable become regular IP with port like `32.45.32.65:12568`
So this regex fails on such kind of client IP.

Solution we use:
Downgrade ddos package, until regex disappear.

Hope this answer can help the author and anyone who face this issue

**Comment by PinnacleOne** [comment]
We have same issue, and we see no choice but downgrade. 
Please resolve this issue in new release

**Comment by rook2pawn** [comment]
@PinnacleOne @MisterHoker @hyrious @tobsbola @abhijeet2015 

5bf50ea6eafb2c87026a02e6f0bc390eb3ec43df

Specifically, it now handles @MisterHoker example, as well as "::1" which is on some systems the loopback.

**Comment by rook2pawn** [comment]
@lumberbeard Can you tell me which address this fails for?

**Comment by rook2pawn** [comment]
@lumberbeard closing this issue. Let me know if the problem still persists (and provide details of the ip failure)
