### ISSUE TITLE
Update programmatic the whitelist

### ISSUE THREAD

**Issue by papac** [rook2pawn/node-ddos#35]
Hello gars,

I want do update incremently the whitelist.

It is possible?

Like this:

```js
app.use(ddos.express(option => {
  let data = await User.find({}, {ip: 1});
  let ips = [];
  for (r of data) {
    ips.push(r.ip); 
  }
  option.whitlist = ips;
  return option; 
}));
```

**Comment by rook2pawn** [comment]
@papac ea4e79f98a56ca223bdd1e4ee8f0a8ee6b0e1cd9

https://github.com/rook2pawn/node-ddos#addwhitelistip

### .addWhitelist(ip)
Update whitelist while running.
```js
    ddos.addWhitelist('74.125.224.72')
```
