### ISSUE TITLE
not compatible with HapiJS v17 

### ISSUE THREAD

**Issue by imbudhiraja** [rook2pawn/node-ddos#36]
Here is my code snippet 

const server = new Hapi.Server({
    host:  localhost,
    port: 3000,
    routes: {
      cors: {
        origin: ['*'],
        additionalHeaders: ['X-Authorization'],
        additionalExposedHeaders: ['X-Authorization'],
      },
      validate: { failAction: handleError },
    },
  });

  await server.register(plugins);

  try {
    server.ext('onRequest', ddos.hapi.bind(ddos));
    await server.start();
    await setIo(server);
    console.log(`+++ Server running at: ${server.info.uri}`);
  } catch (err) {
    console.log(`Error while starting server: ${err.message}`);
  }

Error - 
UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isOriginMatch' of null

**Comment by rook2pawn** [comment]
@imbudhiraja working on new release

**Comment by rook2pawn** [comment]
@imbudhiraja  952b529aa2663aa9a2f5bcf247484006033b604e

https://github.com/rook2pawn/node-ddos#with-hapijs-17

### With [HapiJS 17+](https://hapijs.com/ "HapiJS")

```js
    var Ddos = require('ddos')
    var Hapi = require('hapi');

    var ddos = new Ddos;
    const server = Hapi.server({
      port: 3000,
      host: "localhost"
    });
    server.route({
        method: "GET",
        path: "/",
        handler: (request, h) => {
            return "Hello, world!";
        }
    });
    server.ext("onRequest", ddos.hapi17.bind(ddos));

    server.start()
    .then(() => {

    })

```
