### ISSUE TITLE
Browser's user agent is taken into consideration

### ISSUE THREAD

**Issue by vipersec** [rook2pawn/node-ddos#6]
Hi,

I noticed that browser's user agent is taken into consideration when someone gets denied by this module.

If someone makes a program that sends a huge amount of requests in a small amount of time with different user agent every time he will never get denied and all the requests will pass through.

Something like this (python code):

```
while True:
    opener = urllib2.build_opener()
    opener.addheaders = [('User-agent', 'Mozilla/5.0 ' + 'RANDOM_STRING_HERE')]
    response = opener.open('http://www.foo.bar') 
```

On the other hand, if you ban someone based only on the public IP, whole local networks can be banned because one user got denied. My opinion is to leave it as an option for the developers to decide.

**Comment by danneu** [comment]
Similar issue is that this lib reads from `X-Forwarded-For`: https://github.com/rook2pawn/node-ddos/blob/1ad7a05cde671d65faf9f69712560ac9e61a993e/index.js#L53

`req.ip` in Express and `this.ip` in Koa will only read from `X-Forwarded-For` if you configure them to trust the proxy. 

This library should do the same thing by exposing an option `_params.trustProxy`:

``` javascript
var host = _params.trustProxy
  ? (req.headers['x-forwarded-for'] || req.connection.remoteAddress)
  : req.connection.remoteAddress
```

**Comment by rook2pawn** [comment]
@danneu @vipersec both issues have been addressed. Sorry for the delay, and thanks for the great suggestions.

https://github.com/rook2pawn/node-ddos/commit/c9bdbd9ece4d535129369da740d675143a8b1cc1
